# Generated by Django 3.1.1 on 2020-09-22 20:43

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LeadModel',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('788df35c-ceb2-4281-a22b-7969c1ea8976'), primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('phone', models.CharField(blank=True, max_length=16)),
                ('document_number', models.CharField(blank=True, max_length=14)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
