# Generated by Django 3.1.1 on 2020-09-26 02:23

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('roi_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leadmodel',
            name='id',
            field=models.UUIDField(default=uuid.UUID('97ce48d4-ca7a-484d-91c9-d7533e16d1c1'), primary_key=True, serialize=False),
        ),
    ]
