apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: roi
  namespace: ote
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: roi
  minReplicas: 2
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50
    - type: Resource
      resource:
        name: memory
        target:
          type: AverageValue
          averageValue: 2048Mi
