apiVersion: 'kubernetes-client.io/v1'
kind: ExternalSecret
metadata:
  name: roi
  namespace: ote
spec:
  backendType: secretsManager
  data:
    - key: prod/api/roi
      property: AURORA_DATABASE_URL
      name: AURORA_DATABASE_URL
    - key: prod/api/roi
      property: AWS_ACCESS_KEY_ID
      name: AWS_ACCESS_KEY_ID
    - key: prod/api/roi
      property: AWS_DEFAULT_REGION
      name: AWS_DEFAULT_REGION
    - key: prod/api/roi
      property: AWS_SECRET_ACCESS_KEY
      name: AWS_SECRET_ACCESS_KEY
    - key: prod/api/roi
      property: DEBUG
      name: DEBUG
    - key: prod/api/roi
      property: DISABLE_COLLECTSTATIC
      name: DISABLE_COLLECTSTATIC
    - key: prod/api/roi
      property: ELASTIC_APM_SECRET_TOKEN
      name: ELASTIC_APM_SECRET_TOKEN
    - key: prod/api/roi
      property: ELASTIC_APM_SERVER_URL
      name: ELASTIC_APM_SERVER_URL
    - key: prod/api/roi
      property: ELASTIC_APM_SERVICE_NAME
      name: ELASTIC_APM_SERVICE_NAME
    - key: prod/api/roi
      property: INTERNAL_AUTHENTICATION_API_TOKEN
      name: INTERNAL_AUTHENTICATION_API_TOKEN
    - key: prod/api/roi
      property: INTERNAL_AUTHENTICATION_API_URL
      name: INTERNAL_AUTHENTICATION_API_URL
    - key: prod/api/roi
      property: LOGGERS
      name: LOGGERS
    - key: prod/api/roi
      property: LOG_LEVEL
      name: LOG_LEVEL
    - key: prod/api/roi
      property: OIDC_RSA_PUBLIC_KEY
      name: OIDC_RSA_PUBLIC_KEY
    - key: prod/api/roi
      property: PIP_EXTRA_INDEX_URL
      name: PIP_EXTRA_INDEX_URL
    - key: prod/api/roi
      property: SECRET_KEY
      name: SECRET_KEY
    - key: prod/api/roi
      property: SENTRY_DSN
      name: SENTRY_DSN
    - key: prod/api/roi
      property: SNS_DRY_RUN
      name: SNS_DRY_RUN
    - key: prod/api/roi
      property: WEB_CONCURRENCY
      name: WEB_CONCURRENCY
    - key: prod/api/roi
      property: LOGENTRIES_TOKEN
      name: LOGENTRIES_TOKEN
